### ISSUE TITLE
Add an endpoint for map coordinates

### ISSUE THREAD

**Issue by israellevin** [paket-core/api#25]
We are adding an interactive map to the website which will show locations of events. We need a public (no auth required) endpoint that gets ALL the events (with an optional limit, defaulting to 100). Later we will also add optional time constraints and other filters, but since we want the map ASAP we are not doing it now.

The data needs to be divided into one list that is indexed by packages (escrow_pubkey), and one that is indexed by user_pubkeys for all the non-package related events (which have NULL escrow_pubkey), like "user installed the app", "user launched the app", and so forth (YES, the add_event endpoint is actually going to be useful).

**Comment by yaroslavr-itd** [comment]
Added in commit [4cd9e0bad200cadc34d77122cf6396ccc1def79f](https://github.com/paket-core/api/commit/4cd9e0bad200cadc34d77122cf6396ccc1def79f)
